### ISSUE TITLE
Issue with theme

### ISSUE THREAD

**Issue by ethanolchik** [DagCord/Blizzard#1]
So, im trying out this theme and theres one problem. It's light mode. now i dont know if this is intentional but it makes it suck. pls fix kthx

**Comment by daggy1234** [comment]
Well We have dark mode themes as ell, maybe try those

https://github.com/DagCord/Nord
https://github.com/DagCord/Wildberry

**Comment by ethanolchik** [comment]
we* (lowercase w) well*

ok
