### ISSUE TITLE
Unique Profile Card

### ISSUE THREAD

**Issue by aridutilh** [DagCord/Blizzard#4]
Doesn't have to be an exact replica of this obviously, but I'd love to see some sort of unique profile design 🤔 

![Screen Shot 2021-03-21 at 3 46 45 PM](https://user-images.githubusercontent.com/48355895/111909208-a54f6400-8a5c-11eb-9139-e4a2cf155fe7.png)
![Screen Shot 2021-03-21 at 3 46 57 PM](https://user-images.githubusercontent.com/48355895/111909215-ac767200-8a5c-11eb-8b85-06fc145acf30.png)

**Comment by daggy1234** [comment]
tried something, should be cool
